### ISSUE TITLE
[Refactor] Q and A file file reader add number of docs

### ISSUE THREAD

**Issue by yuye-aws** [Jon-AtAWS/opensearch-ml-quickstart#3]
Instead of main.py, let the reader class had the number of docs.

**Comment by Jon-AtAWS** [comment]
Add a max_questions parameter to questions_for_category, and questions_for_all_categories in qanda_file_reader.py. Default should be -1 (return all docs). Otherwise, return from the generator when it has returned max_questions questions.

**Comment by yuye-aws** [comment]
> Default should be -1 (return all docs)

I remember the default is currently set to 500. Right?

**Comment by yuye-aws** [comment]
Current code is:

`parser.add_argument("-n", "--number_of_docs", default=500, action="store", type=int)`

**Comment by Jon-AtAWS** [comment]
The command line defaults to 500. I think the class should default to all docs.

**Comment by yuye-aws** [comment]
> The command line defaults to 500. I think the class should default to all docs.

Ah I see. the number_of_docs will be passed into the reader class as a parameter.
